all :
	g++ getProductionAsymmetry.cpp -std=c++11 -Wall -Wpedantic -o GetProductionAsymmetry `root-config --libs` `root-config --cflags` -g
	g++ averageAsymmetry.cpp -std=c++11 -Wall -Wpedantic -o AverageAsymmetry /home/pullen/analysis/B02DKstar/Libraries/ParameterReader/libParameterReader.so -I/home/pullen/analysis/B02DKstar/Libraries/ParameterReader/inc -g
