all:
	g++ getEfficiencies.cpp -o GetEfficiencies -Wall -Wpedantic -std=c++11 `root-config --libs` `root-config --cflags`
	g++ getEfficiencies_Kstar.cpp -o GetEfficienciesKstar -Wall -Wpedantic -std=c++11 `root-config --libs` `root-config --cflags`

